### ISSUE TITLE
Semicolons inserted at unexpected locations

### ISSUE THREAD

**Issue by flying-sheep** [decaffeinate/decaffeinate-parser#1]
converting this file:

```coffeescript
a?.b or c
```

yields

```js
((typeof a !== "undefined" && a !== null) ? a.b; : undefined) || c;
```

edit: fixed failing case. also this bug is probably in decaffeinate itself. i get loads of failing test cases that contain too many semicolons

**Comment by eventualbuddha** [comment]
Yep, this is due to decaffeinate turning `a?.b or c` into `(if a? then a.b) or c`, which is then parsed with decaffeinate-parser so that `a.b` is the only statement in a `Block` with the `inline` flag rather than the `consequent` of the `Conditional` node.

**Comment by eventualbuddha** [comment]
A modified version of this problem now fixed in the `patchers` branch:

```
$ echo '(if a then a.b) or c' | ./bin/decaffeinate 
(a ? a.b : undefined) || c;
```

**Comment by eventualbuddha** [comment]
This appears to be working now ([repl](http://decaffeinate-project.org/repl/#?evaluate=true&code=a%3F.b%20or%20c)).
