### ISSUE TITLE
Regexes are treated as identifiers

### ISSUE THREAD

**Issue by eventualbuddha** [decaffeinate/decaffeinate-parser#118]
([repl](http://decaffeinate-project.org/repl/#?evaluate=false&stage=decaffeinate-parser&code=%2Fa%2F))

So far that's not an issue since they are just passed through in decaffeinate, but they should have their own node type.

**Comment by alangpierce** [comment]
👍 I actually just noticed this when working on https://github.com/decaffeinate/decaffeinate/issues/672. I need to do some text replacement within regexes but not identifiers, so getting decaffeinate-parser working right is needed for that.

**Comment by eventualbuddha** [comment]
This was fixed by #120.
