### ISSUE TITLE
How to use "decaffeinate-parser" in the browser?

### ISSUE THREAD

**Issue by bennyn** [decaffeinate/decaffeinate-parser#179]
I would like to use the `decaffeinate-parser` within a web browser (for a frontend page). I got the `decaffeinate-parser.umd.js` file from `node_modules/decaffeinate-parser/dist` but when I try to load this script in the browser I get the following error message:

> Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined
    at decaffeinate-parser.umd.js:7
    at LinesAndColumns (decaffeinate-parser.umd.js:4)
    at decaffeinate-parser.umd.js:5

It complains about this line:

```javascript 
LinesAndColumns = 'default' in LinesAndColumns ? LinesAndColumns['default'] : LinesAndColumns;
```

What can I do in order to make the parser work in a browser?

**Comment by bennyn** [comment]
I got the script to load by patching these lines:

```javascript
LinesAndColumns = 'default' in LinesAndColumns ? LinesAndColumns['default'] : LinesAndColumns;
SourceType = 'default' in SourceType ? SourceType['default'] : SourceType;
var lex__default = 'default' in lex ? lex['default'] : lex;
```

→

```javascript
LinesAndColumns = LinesAndColumns;
SourceType = SourceType;
var lex__default = lex;
```

After that I tried to run the parser by executing `window.decaffeinate.parser.parse('console.log a')`, but it failed with:

> Uncaught TypeError: Cannot read property 'Op' of undefined
    at patchCoffeeScript (decaffeinate-parser.umd.js:2446)
    at Object.parse$1 [as parse] (decaffeinate-parser.umd.js:2521)
    at <anonymous>:1:21

Here is the function it doesn't like:

```javascript
function patchCoffeeScript() {
    decaffeinateCoffeescript_lib_coffeeScript_nodes.Op.prototype.invert = invert;
    decaffeinateCoffeescript_lib_coffeeScript_nodes.Base.prototype.invert = invert;
}
```

**Comment by alangpierce** [comment]
Hi!

The decaffeinate-parser.umd.js file isn't meant to be a browser build, so I think you probably won't be able to get it working by itself. In particular, it doesn't include all of its dependencies, it's just the [rollup](https://github.com/rollup/rollup) output that puts the decaffeinate-parser code into a file that can be used as a node module. That said, it doesn't have any dependencies on node-specific things, so you should be able to include it in a browser build, like the repl does.

I'd take a look at https://github.com/decaffeinate/decaffeinate-project.org, which is where the repl is built. In the [rebuild script](https://github.com/decaffeinate/decaffeinate-project.org/blob/master/script/rebuild), it uses browserify to package decaffeinate and its dependencies (including decaffeinate-parser) into something accessible from the browser. You could probably do something similar with just decaffeinate-parser.

To be honest I haven't worked with browser builds a whole lot, but my understanding is that these days it's best to use a packager like webpack or browserify so you can use regular `require`/`import` and just pull in decaffeinate-parser through npm. But I think you could do a similar thing to do a custom browser build where you can just throw a JS file into a script tag to get an instance of decaffeinate-parser on `window`, if you need to do things that way for whatever reason.

Let me know if that helps!

**Comment by eventualbuddha** [comment]
Browserify is probably your best bet, as @alangpierce said. What are you trying to do?

**Comment by bennyn** [comment]
@eventualbuddha, I am trying to build a website which allows you to convert CoffeeDoc comments into valid JSDoc 3 comments. Therefore I need decaffeinate's parser. I have code working for Node.js but I would like to serve this code on the client-side, so that I don't need to host a Node.js endpoint for making the code conversion.

Parts of my Node.js code look like this:

```javascript
const Comment = require('./jsdoc/Comment');
const lexer = require('coffee-lex');
const parser = require('decaffeinate-parser');
const TagLine = require('./coffeedoc/TagLine');

...

module.exports = function(code) {
  const ast = parser.parse(code);
  const tokens = ast.context.sourceTokens;
  const comments = [];

  tokens.forEach((token) => {
    if (token.type === lexer.SourceType.HERECOMMENT) {
      const {start, end} = token;
      const block = code.substr(start, end);
      const comment = parseBlockComment(block);
      comments.push(comment);
    }
  });

  return comments;
};
```

I thought that I can bundle my code with webpack but I was wrong. When I am trying to do it I get the following error message:

> ERROR in ./decaffeinate-coffeescript/lib/coffee-script/coffee-script.js
Module not found: Error: Can't resolve 'module' in 'D:\dev\projects\bennyn\coffeedoc2jsdoc\node_modules\decaffeinate-coffeescript\lib\coffee-script'
 @ ./decaffeinate-coffeescript/lib/coffee-script/coffee-script.js 129:23-40 169:17-34
 @ ./decaffeinate-parser/dist/decaffeinate-parser.umd.js
 @ ./src/index.js

So I was hoping to find an already bundled `decaffeinate-parser` which can be used in a browser.

**Comment by alangpierce** [comment]
@bennyn Not sure about that error. It looks like CoffeeScript does indeed require the `module` module, which seems to be node-specific, but browserify seems to handle it fine when building the decaffeinate repl. (Really I think it would be easiest to just make a CLI tool instead of a website, but I suppose depends on your use case.)

It may not actually make it easier, but FYI you could probably just use [coffee-lex](https://github.com/decaffeinate/coffee-lex) directly instead of decaffeinate-parser, given that all you need is the tokens. Another option is to just use the CoffeeScript parser/lexer, which I think has a browser build. Also, since you're just looking for block comments, it probably wouldn't be so hard to just parse them yourself. Especially if you're just running it on your own code, it seems very likely that checking for `###` would just work.

Another thing is I noticed that you're using Windows. I think it probably shouldn't affect your case, but FYI both decaffeinate-parser and coffee-lex currently assume LF line endings, and decaffeinate changes the code to LF first and then back to CRLF afterward if necessary.

**Comment by eventualbuddha** [comment]
I'll second @alangpierce's suggestion to just use coffee-lex directly. Here's an example:

https://runkit.com/eventualbuddha/coffee-lex-comment-example
```js
const { default: lex, SourceType } = require('coffee-lex');

const tokens = lex(`
###
# block comment
###

# line comment
a()
`);

tokens.forEach(token => {
  console.log(SourceType[token.type]);
});
```

**Comment by eventualbuddha** [comment]
I'm considering this as answered by saying "use browserify", but feel free to ask follow-up questions if you like.

**Comment by bennyn** [comment]
Thanks @eventualbuddha & @alangpierce for your help! To skip the browserifying part, I just ramped up a small Node.js server (with [express](http://expressjs.com/)) which uses the "decaffeinate-parser" in the background.

On my website I am sending now my CoffeeScript code as a HTTP request to the server, the server then uses the "decaffeinate-parser" npm module and returns the parsed result as a response. This is quite a hack but it was easy to implement (following the claim "Make it work, then make it better"). Next step will be to browserify the "decaffeinate-parser" (as you suggested) so that I can do everything on the client-side (without the need of the Node.js server).

You can find my project (which dies CoffeeDoc to JSDoc 3 conversion) here: https://github.com/bennyn/coffeedoc2jsdoc
