### ISSUE TITLE
Publishing is broken

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate-parser#205]
cc @eventualbuddha 

#193 changed the travis config to do `yarn publish`. However, it looks like `yarn publish` is an interactive CLI that prompts you for the new version number, so the build times out waiting on stdin. As far as I can tell, the only way to make the script non-interactive is to specify `--new-version` as a CLI arg. This is annoying in our case because I think it's sort of hard to get the new version number. Maybe best to just go back to `npm publish`?

Some discussion about this issue here:
https://github.com/yarnpkg/yarn/issues/3011

**Comment by eventualbuddha** [comment]
Yeah, let's just use npm publish.
