### ISSUE TITLE
Can't use with TypeScript 2.9

### ISSUE THREAD

**Issue by eventualbuddha** [decaffeinate/decaffeinate-parser#364]
The change to `keyof` to make it produce not only strings but numbers and symbols means defining `Node#getChildNames` to return `Array<string>` and its subclass overrides returning `Array<keyof this>` does not work. We should fix this somehow.

**Comment by alangpierce** [comment]
Hmmm. I think a quick fix might be to use `Array<keyof this & string>` anywhere we previously were using `Array<keyof this>`. Or we could just give up on the extra validation and do `Array<string>` everywhere.

**Comment by eventualbuddha** [comment]
I think `Array<keyof this & string>` is probably fine. Any downsides you can think of with that?

**Comment by alangpierce** [comment]
My only possible concern is verbosity, but I think it should be fine.
