### ISSUE TITLE
crashing on import without import specifiers

### ISSUE THREAD

**Issue by a-x-** [decaffeinate/decaffeinate-parser#411]
decaffeinate is crashing on my CoffeeScript input:

```coffee
import './Search.sass'
```

[repl](https://decaffeinate-project.org/repl/#?useCS2=true&useJSModules=true&loose=true&evaluate=true&stage=full&code=import%20'.%2FSearch.sass')

I get this error:

```
Expected import clause as the clause for an import declaration.
```

----

Can you pass imports like this as is untouched?

**Comment by eventualbuddha** [comment]
decaffeinate-parser is assuming that there must be an import clause for `ImportDeclaration` nodes, but you can in fact have `import 'foo'` which does not.

https://github.com/decaffeinate/decaffeinate-parser/blob/408d78568751d5c0dd070df0d18e4fae7805932c/src/mappers/mapModuleDeclaration.ts#L35

This will require an update to decaffeinate-coffeescript2 and decaffeinate-parser.

**Comment by a-x-** [comment]
Yay, Thanks!

hm... seems, has not fixed
I use fork with single difference: 5f567dc Revert "fix: disable optional chaining"

1. I pulled new commits (3a54fa7 chore(package): update @types/node to version 11.9.0)
2. updated deps and build: `yarn && yarn build`
3. tried again w/o own back-tick hack on file with `import './Filter.sass'`
```
decaffeinate/bin/decaffeinate --use-cs2 --use-js-modules  --use-optional-chaining --loose --disable-babel-constructor-workaround path/to/file
```

<details><summary>got the same error: `Expected import clause as the clause for an import declaration.`</summary>

```
Error: Expected import clause as the clause for an import declaration.
    at Object.mapModuleDeclaration [as default] (/Users/mxtnr/rocket/felix/frontend/projects/admin/scripts/coffee2es6jsx/decaffeinate/node_modules/decaffeinate-parser/dist/mappers/mapModuleDeclaration.js:14:19)
    at Object.mapAny [as default] (/Users/mxtnr/rocket/felix/frontend/projects/admin/scripts/coffee2es6jsx/decaffeinate/node_modules/decaffeinate-parser/dist/mappers/mapAny.js:124:49)
    at mapChild (/Users/mxtnr/rocket/felix/frontend/projects/admin/scripts/coffee2es6jsx/decaffeinate/node_modules/decaffeinate-parser/dist/mappers/mapBlock.js:74:32)
    at /Users/mxtnr/rocket/felix/frontend/projects/admin/scripts/coffee2es6jsx/decaffeinate/node_modules/decaffeinate-parser/dist/mappers/mapBlock.js:29:45
```

</details>

**Comment by eventualbuddha** [comment]
The changes I've made so far do not actually include any changes to functionality, just a correction of the types. I'll follow up with an actual fix.

**Comment by eventualbuddha** [comment]
Your original example now works if you follow the REPL link.
